# Generated by Django 4.1.5 on 2023-01-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('marka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Samochody.marka')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modele',
            },
        ),
        migrations.CreateModel(
            name='Samochody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('rok', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.TextField()),
                ('marka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Samochody.marka')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Samochody.model')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
    ]
