# Generated by Django 4.1.5 on 2023-01-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Samochody', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Samochody',
            new_name='Samochod',
        ),
    ]
